# Generated by Django 4.1.7 on 2023-02-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_academic', models.CharField(max_length=6, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('cve_sexo', models.CharField(max_length=9)),
                ('cve_campus', models.CharField(max_length=3)),
                ('cve_institu', models.CharField(max_length=3)),
                ('cve_program', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'academic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catacurs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cve_campus', models.CharField(max_length=3)),
                ('cve_program', models.CharField(max_length=3)),
                ('cve_curso', models.CharField(max_length=6, unique=True)),
                ('gpo_670', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('credimi', models.IntegerField()),
                ('credima', models.IntegerField()),
                ('vigente', models.CharField(blank=True, max_length=2, null=True)),
                ('es_tecno', models.CharField(blank=True, max_length=1, null=True)),
                ('periodo', models.CharField(max_length=9)),
                ('agno', models.IntegerField()),
                ('hay_credi', models.CharField(blank=True, max_length=2, null=True)),
                ('hay_calif', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo', models.CharField(max_length=16)),
                ('isevaluated', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catacurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capcurs', models.IntegerField()),
                ('cve_curso', models.CharField(max_length=6)),
                ('nom_curso', models.CharField(max_length=120)),
                ('cve_academic', models.CharField(max_length=6)),
                ('nom_academic', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horapractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capcurs', models.IntegerField()),
                ('cve_curso', models.CharField(max_length=6)),
                ('nom_curso', models.CharField(max_length=120)),
                ('lunes', models.TimeField()),
                ('martes', models.TimeField()),
                ('miercoles', models.TimeField()),
                ('jueves', models.TimeField()),
                ('viernes', models.TimeField()),
                ('aula', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'horapractica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imparegu',
            fields=[
                ('num_emplea', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cve_academic', models.CharField(max_length=6)),
                ('cve_curso', models.CharField(max_length=6)),
                ('gpo_670', models.CharField(max_length=2)),
                ('periodo', models.CharField(max_length=9)),
                ('agno', models.IntegerField()),
                ('participa', models.CharField(max_length=11)),
                ('registro', models.DateField()),
                ('per_vi_cur', models.CharField(max_length=9)),
                ('ano_vi_cur', models.IntegerField()),
                ('dis_cre', models.FloatField()),
            ],
            options={
                'db_table': 'imparegu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_campus', models.CharField(max_length=3)),
                ('cve_posgrad', models.CharField(max_length=6)),
                ('nom_posgra', models.CharField(max_length=60)),
                ('cve_program', models.CharField(max_length=3)),
                ('nom_program', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capcurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_curso', models.CharField(max_length=120)),
                ('nom_academic', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('participacion', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('lunes', models.TimeField()),
                ('martes', models.TimeField()),
                ('miercoles', models.TimeField()),
                ('jueves', models.TimeField()),
                ('viernes', models.TimeField()),
                ('aula', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=120)),
                ('cve_academic', models.ForeignKey(db_column='cve_academic', on_delete=django.db.models.deletion.DO_NOTHING, to='capcursapp.academic', to_field='cve_academic')),
                ('cve_curso', models.ForeignKey(db_column='cve_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='capcursapp.catacurs', to_field='cve_curso')),
            ],
            options={
                'db_table': 'capcurs',
                'managed': True,
            },
        ),
    ]
