# Generated by Django 4.1.7 on 2023-02-28 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capcurs',
            old_name='jueves',
            new_name='jueves_fin',
        ),
        migrations.RenameField(
            model_name='capcurs',
            old_name='lunes',
            new_name='jueves_ini',
        ),
        migrations.RenameField(
            model_name='capcurs',
            old_name='martes',
            new_name='lunes_fin',
        ),
        migrations.RenameField(
            model_name='capcurs',
            old_name='miercoles',
            new_name='lunes_ini',
        ),
        migrations.RenameField(
            model_name='capcurs',
            old_name='viernes',
            new_name='martes_fin',
        ),
        migrations.AddField(
            model_name='capcurs',
            name='martes_ini',
            field=models.TimeField(default=datetime.datetime(2023, 2, 28, 19, 45, 21, 286831, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capcurs',
            name='miercoles_fin',
            field=models.TimeField(default=datetime.datetime(2023, 2, 28, 19, 45, 37, 238905, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capcurs',
            name='miercoles_ini',
            field=models.TimeField(default=datetime.datetime(2023, 2, 28, 19, 45, 41, 160456, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capcurs',
            name='viernes_fin',
            field=models.TimeField(default=datetime.datetime(2023, 2, 28, 19, 45, 53, 943165, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capcurs',
            name='viernes_ini',
            field=models.TimeField(default=datetime.datetime(2023, 2, 28, 19, 45, 56, 327635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
