# Generated by Django 4.1.7 on 2023-02-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0002_rename_jueves_capcurs_jueves_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capcurs',
            options={'managed': False},
        ),
    ]
