# Generated by Django 4.1.7 on 2023-02-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0003_alter_capcurs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capcurs',
            options={'managed': True},
        ),
    ]
