# Generated by Django 4.1.7 on 2023-03-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0005_coordinaciones_delete_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinaciones',
            table='coordinaciones',
        ),
    ]
