# Generated by Django 4.1.7 on 2023-03-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0006_alter_coordinaciones_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capcurs',
            old_name='nom_curso',
            new_name='nombre',
        ),
    ]
