# Generated by Django 4.1.7 on 2023-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0007_rename_nom_curso_capcurs_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capcurs',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
