# Generated by Django 4.1.7 on 2023-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0008_alter_capcurs_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capcurs',
            options={'managed': False},
        ),
    ]
