# Generated by Django 4.1.7 on 2023-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capcursapp', '0009_alter_capcurs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imparegubda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_emplea', models.BigIntegerField()),
                ('cve_academic', models.CharField(max_length=6)),
                ('cve_curso', models.CharField(max_length=7)),
                ('gpo_670', models.CharField(max_length=2)),
                ('periodo', models.CharField(max_length=9)),
                ('agno', models.IntegerField()),
                ('participa', models.CharField(max_length=11)),
                ('registro', models.DateField(blank=True, null=True)),
                ('per_vi_cur', models.CharField(max_length=9)),
                ('ano_vi_cur', models.IntegerField()),
                ('dis_cre', models.FloatField()),
                ('isevaluated', models.IntegerField(blank=True, db_column='IsEvaluated', null=True)),
            ],
            options={
                'db_table': 'imparegubda',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='capcurs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='horapractica',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imparegu',
            options={'managed': True},
        ),
    ]
